//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AzureListaClientes.Azure {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GuardarOperationCompleted;
        
        private System.Threading.SendOrPostCallback BusquedaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarIMCOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarIMCOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback BusquedaLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback SignUp_ExFOperationCompleted;
        
        private System.Threading.SendOrPostCallback CountLogin_ExFOperationCompleted;
        
        private System.Threading.SendOrPostCallback NoSignUp_ExFOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = "https://alvarom.azurewebsites.net/WebService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GuardarCompletedEventHandler GuardarCompleted;
        
        /// <remarks/>
        public event BusquedaCompletedEventHandler BusquedaCompleted;
        
        /// <remarks/>
        public event ActualizarCompletedEventHandler ActualizarCompleted;
        
        /// <remarks/>
        public event GuardarIMCCompletedEventHandler GuardarIMCCompleted;
        
        /// <remarks/>
        public event BuscarIMCCompletedEventHandler BuscarIMCCompleted;
        
        /// <remarks/>
        public event GuardarLoginCompletedEventHandler GuardarLoginCompleted;
        
        /// <remarks/>
        public event BusquedaLoginCompletedEventHandler BusquedaLoginCompleted;
        
        /// <remarks/>
        public event SignUp_ExFCompletedEventHandler SignUp_ExFCompleted;
        
        /// <remarks/>
        public event CountLogin_ExFCompletedEventHandler CountLogin_ExFCompleted;
        
        /// <remarks/>
        public event NoSignUp_ExFCompletedEventHandler NoSignUp_ExFCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Guardar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Guardar(double Numero, double Saldo) {
            object[] results = this.Invoke("Guardar", new object[] {
                        Numero,
                        Saldo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarAsync(double Numero, double Saldo) {
            this.GuardarAsync(Numero, Saldo, null);
        }
        
        /// <remarks/>
        public void GuardarAsync(double Numero, double Saldo, object userState) {
            if ((this.GuardarOperationCompleted == null)) {
                this.GuardarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarOperationCompleted);
            }
            this.InvokeAsync("Guardar", new object[] {
                        Numero,
                        Saldo}, this.GuardarOperationCompleted, userState);
        }
        
        private void OnGuardarOperationCompleted(object arg) {
            if ((this.GuardarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarCompleted(this, new GuardarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Busqueda", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Busqueda(double Numero) {
            object[] results = this.Invoke("Busqueda", new object[] {
                        Numero});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void BusquedaAsync(double Numero) {
            this.BusquedaAsync(Numero, null);
        }
        
        /// <remarks/>
        public void BusquedaAsync(double Numero, object userState) {
            if ((this.BusquedaOperationCompleted == null)) {
                this.BusquedaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBusquedaOperationCompleted);
            }
            this.InvokeAsync("Busqueda", new object[] {
                        Numero}, this.BusquedaOperationCompleted, userState);
        }
        
        private void OnBusquedaOperationCompleted(object arg) {
            if ((this.BusquedaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BusquedaCompleted(this, new BusquedaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Actualizar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Actualizar(double Numero, double Saldo) {
            object[] results = this.Invoke("Actualizar", new object[] {
                        Numero,
                        Saldo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarAsync(double Numero, double Saldo) {
            this.ActualizarAsync(Numero, Saldo, null);
        }
        
        /// <remarks/>
        public void ActualizarAsync(double Numero, double Saldo, object userState) {
            if ((this.ActualizarOperationCompleted == null)) {
                this.ActualizarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarOperationCompleted);
            }
            this.InvokeAsync("Actualizar", new object[] {
                        Numero,
                        Saldo}, this.ActualizarOperationCompleted, userState);
        }
        
        private void OnActualizarOperationCompleted(object arg) {
            if ((this.ActualizarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarCompleted(this, new ActualizarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarIMC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GuardarIMC(string Nombre, double Peso, double Estatura, double Resultado, string Estado) {
            object[] results = this.Invoke("GuardarIMC", new object[] {
                        Nombre,
                        Peso,
                        Estatura,
                        Resultado,
                        Estado});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarIMCAsync(string Nombre, double Peso, double Estatura, double Resultado, string Estado) {
            this.GuardarIMCAsync(Nombre, Peso, Estatura, Resultado, Estado, null);
        }
        
        /// <remarks/>
        public void GuardarIMCAsync(string Nombre, double Peso, double Estatura, double Resultado, string Estado, object userState) {
            if ((this.GuardarIMCOperationCompleted == null)) {
                this.GuardarIMCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarIMCOperationCompleted);
            }
            this.InvokeAsync("GuardarIMC", new object[] {
                        Nombre,
                        Peso,
                        Estatura,
                        Resultado,
                        Estado}, this.GuardarIMCOperationCompleted, userState);
        }
        
        private void OnGuardarIMCOperationCompleted(object arg) {
            if ((this.GuardarIMCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarIMCCompleted(this, new GuardarIMCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarIMC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet BuscarIMC(string Nombre, int Dia, string Mes) {
            object[] results = this.Invoke("BuscarIMC", new object[] {
                        Nombre,
                        Dia,
                        Mes});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarIMCAsync(string Nombre, int Dia, string Mes) {
            this.BuscarIMCAsync(Nombre, Dia, Mes, null);
        }
        
        /// <remarks/>
        public void BuscarIMCAsync(string Nombre, int Dia, string Mes, object userState) {
            if ((this.BuscarIMCOperationCompleted == null)) {
                this.BuscarIMCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarIMCOperationCompleted);
            }
            this.InvokeAsync("BuscarIMC", new object[] {
                        Nombre,
                        Dia,
                        Mes}, this.BuscarIMCOperationCompleted, userState);
        }
        
        private void OnBuscarIMCOperationCompleted(object arg) {
            if ((this.BuscarIMCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarIMCCompleted(this, new BuscarIMCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GuardarLogin(string Nombre, string Domicilio, string Correo, int Edad, double Saldo) {
            object[] results = this.Invoke("GuardarLogin", new object[] {
                        Nombre,
                        Domicilio,
                        Correo,
                        Edad,
                        Saldo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarLoginAsync(string Nombre, string Domicilio, string Correo, int Edad, double Saldo) {
            this.GuardarLoginAsync(Nombre, Domicilio, Correo, Edad, Saldo, null);
        }
        
        /// <remarks/>
        public void GuardarLoginAsync(string Nombre, string Domicilio, string Correo, int Edad, double Saldo, object userState) {
            if ((this.GuardarLoginOperationCompleted == null)) {
                this.GuardarLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarLoginOperationCompleted);
            }
            this.InvokeAsync("GuardarLogin", new object[] {
                        Nombre,
                        Domicilio,
                        Correo,
                        Edad,
                        Saldo}, this.GuardarLoginOperationCompleted, userState);
        }
        
        private void OnGuardarLoginOperationCompleted(object arg) {
            if ((this.GuardarLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarLoginCompleted(this, new GuardarLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BusquedaLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet BusquedaLogin(int Folio) {
            object[] results = this.Invoke("BusquedaLogin", new object[] {
                        Folio});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void BusquedaLoginAsync(int Folio) {
            this.BusquedaLoginAsync(Folio, null);
        }
        
        /// <remarks/>
        public void BusquedaLoginAsync(int Folio, object userState) {
            if ((this.BusquedaLoginOperationCompleted == null)) {
                this.BusquedaLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBusquedaLoginOperationCompleted);
            }
            this.InvokeAsync("BusquedaLogin", new object[] {
                        Folio}, this.BusquedaLoginOperationCompleted, userState);
        }
        
        private void OnBusquedaLoginOperationCompleted(object arg) {
            if ((this.BusquedaLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BusquedaLoginCompleted(this, new BusquedaLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SignUp_ExF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SignUp_ExF(string usr, string psw) {
            object[] results = this.Invoke("SignUp_ExF", new object[] {
                        usr,
                        psw});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SignUp_ExFAsync(string usr, string psw) {
            this.SignUp_ExFAsync(usr, psw, null);
        }
        
        /// <remarks/>
        public void SignUp_ExFAsync(string usr, string psw, object userState) {
            if ((this.SignUp_ExFOperationCompleted == null)) {
                this.SignUp_ExFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSignUp_ExFOperationCompleted);
            }
            this.InvokeAsync("SignUp_ExF", new object[] {
                        usr,
                        psw}, this.SignUp_ExFOperationCompleted, userState);
        }
        
        private void OnSignUp_ExFOperationCompleted(object arg) {
            if ((this.SignUp_ExFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SignUp_ExFCompleted(this, new SignUp_ExFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CountLogin_ExF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet CountLogin_ExF(string usr, string psw) {
            object[] results = this.Invoke("CountLogin_ExF", new object[] {
                        usr,
                        psw});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void CountLogin_ExFAsync(string usr, string psw) {
            this.CountLogin_ExFAsync(usr, psw, null);
        }
        
        /// <remarks/>
        public void CountLogin_ExFAsync(string usr, string psw, object userState) {
            if ((this.CountLogin_ExFOperationCompleted == null)) {
                this.CountLogin_ExFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCountLogin_ExFOperationCompleted);
            }
            this.InvokeAsync("CountLogin_ExF", new object[] {
                        usr,
                        psw}, this.CountLogin_ExFOperationCompleted, userState);
        }
        
        private void OnCountLogin_ExFOperationCompleted(object arg) {
            if ((this.CountLogin_ExFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CountLogin_ExFCompleted(this, new CountLogin_ExFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NoSignUp_ExF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet NoSignUp_ExF(string usr) {
            object[] results = this.Invoke("NoSignUp_ExF", new object[] {
                        usr});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void NoSignUp_ExFAsync(string usr) {
            this.NoSignUp_ExFAsync(usr, null);
        }
        
        /// <remarks/>
        public void NoSignUp_ExFAsync(string usr, object userState) {
            if ((this.NoSignUp_ExFOperationCompleted == null)) {
                this.NoSignUp_ExFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNoSignUp_ExFOperationCompleted);
            }
            this.InvokeAsync("NoSignUp_ExF", new object[] {
                        usr}, this.NoSignUp_ExFOperationCompleted, userState);
        }
        
        private void OnNoSignUp_ExFOperationCompleted(object arg) {
            if ((this.NoSignUp_ExFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NoSignUp_ExFCompleted(this, new NoSignUp_ExFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GuardarCompletedEventHandler(object sender, GuardarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void BusquedaCompletedEventHandler(object sender, BusquedaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BusquedaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BusquedaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ActualizarCompletedEventHandler(object sender, ActualizarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GuardarIMCCompletedEventHandler(object sender, GuardarIMCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarIMCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarIMCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void BuscarIMCCompletedEventHandler(object sender, BuscarIMCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarIMCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarIMCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GuardarLoginCompletedEventHandler(object sender, GuardarLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void BusquedaLoginCompletedEventHandler(object sender, BusquedaLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BusquedaLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BusquedaLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void SignUp_ExFCompletedEventHandler(object sender, SignUp_ExFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SignUp_ExFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SignUp_ExFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CountLogin_ExFCompletedEventHandler(object sender, CountLogin_ExFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CountLogin_ExFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CountLogin_ExFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void NoSignUp_ExFCompletedEventHandler(object sender, NoSignUp_ExFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NoSignUp_ExFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NoSignUp_ExFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591